ALL_COLUMNS = [
    "Getätigt am Datum",
    "Betrag",
    "Quelle",
    "Zahlungsweise",
    "Projekt",
    "Kontakt-ID",
    "Vorname",
    "Nachname",
    "Unternehmen",
    "Möchte Brief-Mailing",
    "Möchte E-Mail-Newsletter",
    "Keine E-Mails senden",
    "Keine Briefe senden",
    "Keine Anrufe",
    "Geburtsdatum",
    "Kontakt-Tags",
    "Person erstellt am",
    "PLZ",
    "Stadt",
    "Land",
    "E-Mail-Adresse",
    "Telefon",
    "02-Anredeform",
]